### ISSUE TITLE
Where to download the VCGplus 110k original video?

### ISSUE THREAD

**Issue by lucasjinreal** [mbzuai-oryx/VideoGPT-plus#2]
Where to download the VCGplus 110k original video?

**Comment by mmaaz60** [comment]
Hi @lucasjinreal,

I appreciate your interest in our work. The videos used to create VCG+112K are same as used in [Video-ChatGPT](https://github.com/mbzuai-oryx/Video-ChatGPT/issues/98#issuecomment-2066219023).

Alternatively, you can download these videos from our [video annotation pipeline](https://huggingface.co/datasets/MBZUAI/video_annotation_pipeline/blob/main/activitynet_videos.tgz) HuggingFace page as well.

Please let me know if you face any issues. Good Luck! and thank you.

**Comment by lucasjinreal** [comment]
Hi. I saw the gogole link you provided has about 160GB, which is soooo big, did you have a splited version whcih can be directly used for training?

**Comment by lucasjinreal** [comment]
Is the activity_net.video.tar.gz is videos used for trainig?

**Comment by mmaaz60** [comment]
Hi @lucasjinreal,

Thank you for your interest in our work. Please note that both the videos (provided through google drive link) and `activity_net.video.tar.gz` are same, however `activity_net.video.tar.gz` is the compressed version.

In short, you can use `activity_net.video.tar.gz`. Thank You and Good Luck!

**Comment by lucasjinreal** [comment]
@mmaaz60  Hi, does the uncompress video is same? Or the video is being compressed like resized?

**Comment by mmaaz60** [comment]
Hi @lucasjinreal,

My apologies, I missed your message. Yes, the videos in `activity_net.video.tar.gz` are stored at a lower resolution and lower frame rate. However, as per our experiments, it did not affect the final performance.

If you want to use the original videos, you can download them using the google drive link I share [here](https://github.com/mbzuai-oryx/Video-ChatGPT/issues/98#issuecomment-2066219023). Good Luck and Thank You.
