### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by vvirgooo2** [mbzuai-oryx/VideoGPT-plus#26]
Hi, thanks for your awesome work! I want to know why training two models for 2（VGG and MV）benchmarks? Why not use all the data to train a single model. Looking forward to your reply!
![image](https://github.com/user-attachments/assets/65f29adc-63e3-4d3b-9ff2-51488cbbed50)

**Comment by mmaaz60** [comment]
Hi @vvirgooo2,

Thank you for your interest in our work. In our experiments we have found that training a single model on combined data  (using FINETUNE configuration at https://github.com/mbzuai-oryx/VideoGPT-plus/blob/0422b91fda488dab7831f5c0043ad5be051be5fd/videogpt_plus/config/__init__.py#L6C6-L6C16) results in a model equally good on both MVBench and VCGBecnh benchmarks. We will update our technical report and release the updated checkpoints soon.

**Comment by vvirgooo2** [comment]
Thanks for your reply!
