### ISSUE TITLE
full-parameter or lora?

### ISSUE THREAD

**Issue by Nastu-Ho** [mbzuai-oryx/VideoGPT-plus#3]
Will full-parameter fine-tuning be better?

**Comment by mmaaz60** [comment]
Hi @Nastu-Ho,

As per our experiments, we did not notice any accuracy gains when using Phi3-mini-4K LLM or Vicuna. However, full fine-tuning was better in the case of LLaMA-3 as compared to LoRA.

**Comment by Nastu-Ho** [comment]
≈

> Hi @Nastu-Ho,
> 
> As per our experiments, we did not notice any accuracy gains when using Phi3-mini-4K LLM or Vicuna. However, full fine-tuning was better in the case of LLaMA-3 as compared to LoRA.


Thank you for your reply.
One thing I'm curious about is whether a stronger LLM can continue to bring improvements in mvbench.
The problem I am currently encountering is that my model has been replaced with a stronger LLM (qwen2, mistral) and has not been significantly improved like videochat2.
So I'm curious about the performance of your method using different LLMs (such as LLaMA3, mistral) on mvbench?

**Comment by mmaaz60** [comment]
Hi @Nastu-Ho,

We do not have the MVBench results using LLaMA-3 LLM, however, I can share the numbers with Vicuna 7B and 13B that we observe during experiments and this may give us some clues about the trend.

With Vicuna 7B and 13B, we obtain 53.10 and 58.67 average scores on MVBench. These experiments show that using a better/stronger LLM improves the MVBench performance. However, we do not have any ablations with LLaMA-3 and Mistral. 

If you have any findings, please do share. Thank You.

**Comment by Nastu-Ho** [comment]
Hey, I want to know how many frames a video is sampled during the training process? 
If the number of samples is fixed, how many visual tokens will be input to LLM for a video?

**Comment by mmaaz60** [comment]
Hi @Nastu-Ho,

We sample 16 frames for `VCGBench_FINETUNING` training and 8 frames for `MVBench_FINETUNING` training.

For video branch, the features per frame are 64 and for image branch the features per frame are 144. So in total for 8 frame configuration, the total number of vision tokens is 64x8+144x8=1664.

I hope it will help.
